### ISSUE TITLE
Too many update to Damcon UI making UI unusable

### ISSUE THREAD

**Issue by abrindam** [abrindam/ArtemisEngineeringClient#15]
We update the damcon UI on every network packet. This is causing close to 200% CPU usage on my computer and is making command not take for minutes at a time.

**Comment by abrindam** [comment]
Worth noting this does NOT happen in fake mode as change events are generated more reasonably there.

**Comment by jacobmaxfrank** [comment]
Can we put the netcode in its own thread? Is it already? I haven't looked at it much.

I haven't done any optimization so we could look into that if no easier options are available and rate limiting won't work.

The minimum server tick rate is 1 tick every 20 ms, right?

**Comment by abrindam** [comment]
Netcode is in its own thread (that's handled by the protocol library) Not 100% sure what was happening, possibly netcode thread was being starved. 

The fix is we need to fire a change event to the UI layer when something it cares about changes, rather than on EVERY packet which could be due to really anything (possibly even including heartbeats).
